/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import NavBar from "~/components/Navbar";
import Cpu from "~/components/parts/Cpu";
import MotherBoard from "~/components/parts/Motherboard";
import Image from "next/image";

export type Part = {
    brand: string;
    model: string;
    price: number;
    image: string;
    stock: number;
} | null


export default function Builder() {

    return (
        <>
            <Head>
                <title>Builder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="bg-slate-900 min-h-screen">
                <div className="mx-auto grid max-w-2xl grid-cols-1 items-center gap-x-8 gap-y-16 px-4 py-24 sm:px-6 sm:py-32 lg:max-w-7xl lg:grid-cols-2 lg:px-8">
                    <div>
                        <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">Pc Builder</h2>
                        <p className="mt-4 text-white">
                            Welcome to our PC Builder module, where you can create your dream computer from scratch! Our easy-to-use platform lets you select every component of your PC, from the motherboard and processor to the graphics card and storage.
                        </p>
                        <Cpu />
                        <MotherBoard />
                    </div>
                    <Image
                        src="/assets/build.svg"
                        alt="PC Builder"
                        width={500}
                        height={500}
                    />
                </div>
            </div>
        </>
    )
}