import Head from "next/head";
import { useEffect } from "react";
import NavBar from "~/components/Navbar";
import Table from "~/components/table/Table";

export default function Builder() {
    useEffect(() => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        import('preline')
    }, [])

    return (
        <>
            <Head>
                <title>Builder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div className="bg-slate-800">
                <Table />
            </div>
        </>
    )
}